= Chroniques d'un introverti en télétravail
Cédric Champeau
2019-09-29
:jbake-type: post
:jbake-tags: télétravail, introversion
:jbake-status: published
:source-highlighter: pygments
:id: introvert-remote
:linkattrs:

L'autre jour j'écoutais le podcast https://lescastcodeurs.com/2019/09/16/lcc-216-l-episode-ou-on-a-perdu-le-compte/[Les Cast Codeurs] qui abordait le sujet du télétravail.
Quelques remarques m'ont fait tiquer, je m'en vais donc ici vous raconter mon expérience, mais surtout vous parler de moi et de l'introversion.

## Le télétravail et l'introversion

Voici maintenant presque 10 ans que je suis presque à 100% en télétravail. Je dis presque, parce qu'en pratique, j'ai quelques déplacements professionnels (conférences, meetings) de temps en temps, mais pour mon boulot de tous les jours, c'est tout à la maison.
Avant de faire du télétravail, je roulais beaucoup: mon emploi était sur Nantes, à 45km de chez moi. Ca faisait donc 90km par jour, mais surtout entre 2 et 3h de transport par jour (eh oui, j'avais la chance de devoir traverser le pont de Cheviré, pour ceux qui connaissent...).
Bref, le jour où j'ai changé d'emploi, pour passer chez VMware pour travailler sur le langage Groovy, le premier choc pour moi ça a été de récupérer ces 2 ou 3 heures par jour.
C'est autant de temps qu'on peut passer à s'occuper de ses enfants (les déposer à l'école, les emmener au sport, ...) ou à faire des activités à la maison (jardinage, sport, ...).
Je ne reviendrais pas sur ces aspects, parce qu'ils sont largement connus, le seul "inconvénient" pour moi étant surtout d'être capable de maîtriser ses horaires, c'est à dire de ne pas, contrairement à ce qu'on pense, faire _trop_ d'heures !

Non, ce sur quoi je veux revenir, c'est cette remarque d'Antonio Goncalvés, qui, en conseil, dit en substance:

"Balancez votre cafetière, sortez dans les bars, voyez des gens, c'est important de voir des êtres humains!"

Et ceci https://twitter.com/CedricChampeau/status/1173893698997936130[m'a fait réagir], j'aimerais donc revenir sur le sujet.
Tout d'abord, revenons sur le fait que ce conseil ne fonctionne que si vous habitez en ville, ce qui n'est pas mon cas.
Je suis en campagne, à 5km du bourg, donc faire une "pause café", ça prend du temps dans ces conditions.

Mais revenons surtout sur le fond du sujet: "C'est important de voir des êtres humains", ou ce _besoin de ne pas être seul_.
C'est un sujet qui me tient à coeur et qui résonne avec une des questions que j'ai souvent lorsque je parle du télétravail:

"Mais tu n'en as pas marre d'être tout seul, de ne voir personne ?"

Alors, répondons franchement: **non**.

Autant je comprends les personnes qui en ont besoin, autant, **ne croyez pas que tout le monde fonctionne comme vous** et a _besoin_ de voir du monde.
Certaines personnes, comme moi, vivent très bien sans voir personne.
Je peux passer des journées entières seul, sans que celà ne me pose le moindre problème, ni ne me cause le quelconque manque de relations humaines.

Je vais partie de cette catégorie de population qu'on appelle les _introvertis_.

Un _introverti_, contrairement à une croyance populaire, ça n'est pas un associal, un égoïste ou quelqu'un sans empathie.

Un _introverti_, c'est quelqu'un dont l'énergie sera drainée par la foule, par les relations inter-personnelles, c'est l'opposé d'un _extraverti_ qui a besoin de monde pour regagner de l'énergie.

Un _introverti_, c'est quelqu'un qui ne supportera pas les conversations de comptoir, parce qu'elles ne lui apportent rien d'autre qu'une perte d'énergie.

Un _introverti_, c'est quelqu'un qui pourra vous tenir une conversation passionnée sur un sujet qui l'intéresse, parce qu'il en retire quelque chose: l'interaction en vaut la chandelle.
  
Déja tout petit, j'évitais les groupes, je n'avais pas beaucoup d'amis (mais ceux que j'avais à l'époque, je les ai toujours).
J'ai toujours eu une peur bleue de me retrouver dans un groupe où je ne connaissais personne, que ce soit à l'école, au sport, ...
Mais même si je connaissais quelqu'un, se retrouver _dans un groupe_, à devoir cultiver des relations proches, extra "professionnelles", était d'une extrême complexité pour moi (et ça l'est toujours).
Tout ce qui m'importait à l'époque, c'était d'apprendre, être "fort" à l'école, ce qui m'a valu d'être traité "d'intello", parfois chahuté, ou d'avoir des remarques pas particulièrement gentilles d'autres élèves au dos de ma photo de classe, ceci pendant une grande partie de mon enfance...

Par exemple, j'ai toujours refusé les camps de vacances (ma seule expérience, une semaine à faire du cheval, fût tellement une horreur pour moi que je m'en souviens encore).
J'ai aussi refusé toutes les classes de neige.
En revanche, j'avais accepté d'aller en voyage scolaire en Angleterre, en Irlande, en Espagne, non sans lutter contre moi-même, parce que je savais que je pouvais en tirer quelque chose, mais aussi parce que j'avais la garantie de me retrouver en petit nombre, avec un copain, dans une chambre...

Dans la même veine, devoir se retrouver au tableau pour réciter une poésie, ou, pire, chanter, tenait de la torture.
J'ai adoré la fac' de sciences, parce que je pouvais passer du temps au "café" avec 2/3 potes maximum, à discuter.
J'ai détesté mon école d'ingénieur, où j'ai du rivaliser d'astuces pour éviter les soirées d'intégration, tonus et autres dont étaient friants 95% des étudiants: se faire reconnaître sans se faire exclure (mais j'ai encore trouvé quelques bons amis que je tiens de cette époque).

Aaah, les soirées d'intégration: ce qui est marrant pour certains, se bourrer la gu..., humilier "gentilement" les autres, c'était juste pour moi quelque chose d'horrible.
Tiens, d'ailleurs, peu le savent, mais j'ai fait toute ma scolarité à Nantes, non pas parce que tout était disponible là bas (c'était le case), mais parce que j'était terrifié à l'idée de me retrouver seul dans une FAC, une école d'ingénieur, à l'autre bout de la France...
Certains profs m'avaient reproché de ne pas tenter une "Grande Ecole", mais je pense qu'au final, je m'en suis plutôt bien sorti !

## Jamais je n'embaucherais quelqu'un comme vous!

Ceci pourrait vous paraitre surprenant pour quelqu'un qui, aujourd'hui, donne des conférences devant, parfois, des centaines de personnes.
Mais alors, quelle est la différence ?

La différence, c'est que lorsque je vous parle dans un cadre professionnelle, **je maîtrise mon sujet** (ou je pense le maîtriser, ah ah !).
Je peux vous parler ouvertement, parce que je sais que les questions qu'on va me poser seront sur ce sujet.
Il n'y a que peu de place à l'inconnu.

C'est aussi pour celà qu'il m'est très difficile, encore aujourd'hui, d'aborder des gens que je ne connais pas.
Je ne sais pas faire de "small talk", comme on dit.
Mais ça va plus loin: j'ai fais pas mal de déplacements à l'étranger, aux US par exemple, mais JAMAIS, je ne suis sorti seul pour visiter (au mieux je marcherai une heure ou deux dans les alentours).
On rentre dans cette zone d'inconnu qui me met tellement mal à l'aise : devoir s'adresser à des gens, qui plus est à l'étranger, pour commander un plat, pour demander son chemin: celà me demande trop d'efforts, me draine trop.
En revanche, si je connais une ou deux personnes et qu'elle me proposent de les accompagner, ça se passera bien: j'apprécie fortement une sortie en "petit comité".
Tout le monde me dit que j'ai tellement de chance de partir voyager, voir du pays, mais moi, je déteste tellement voyager, en tout cas sans ma famille...
Rien qu'aller à Paris, me rendre compte du nombre de personnes qui vivent là bas, me sentir étouffer, qu'est-ce que j'ai horreur de ça !

La conséquence, c'est que je fuis comme la peste les "soirées" comme les speaker dinner, les événements d'entreprise, ...
Souvent, on les présente comme des incontournables du "réseautage", et c'est vrai qu'on y apprend souvent des choses intéressantes, mais elles sont extrêmement stressantes pour moi.
La plupart du temps, j'essaie de trouver une tête connue et je "m'accroche", mais je ne fais jamais long feu.
Ce qui me terrorise s'est d'en arriver à des sujets extra-professionnels, là où je n'ai AUCUNE "compétence".
Certains diront que je suis chiant, que je n'ai aucun intérêt, et c'est probablement vrai si vous recherchez quelqu'un à la vie extraordinaire, la mienne n'est pas ultra passionnante :)

Si vous en arrivez là, vous devez vous dire que je ne dois pas être un très bon "team player", comme on dit.
Paradoxalement je ne pense pas que ce soit le cas.
En effet, il ne faut pas confondre mon incapacité à avoir des relations inter-personnelles "simples" avec la capacité d'échange, d'interaction professionnelle, qui est sur une toute autre dimension.

Comme je vous l'ai expliqué, je donne régulièrement des talks, et j'adore plus que tout partager ces connaissances, aider les autres.
J'aime aussi travailler avec des gens plus compétents que moi pour avoir l'autre face de la pièce: apprendre, comprendre de nouvelles choses, progresser.
Et dans ce contexte, travailler en équipe aide énormément.

Alors, ce n'est pas parce qu'on est en télétravail et qu'on ne voit personne qu'on travaille _seul_.
Non, on est en équipe. On fait des "daily standup" (via Hangout/Slack), on s'organise, on fait des petites réunions "face to face" de temps en temps, bref, je pense, mes collègues vous le diront si ça n'est pas le cas, que ça se passe plutôt bien.

Bref, n'ayez pas peur de cet aspect: la solitude n'est pas, pour tout le monde, un problème.
Elle peut, au contraire, aider à la productivité: pas de réunionite inutile, capacité à se focaliser sur un problème des heures durant, ...
Elle n'est pas, non plus, signe de quelqu'un qui ne peut pas travailler en équipe: ça n'empêche en RIEN d'aider ses collègues, ses clients, bien au contraire: puisqu'on sait que la relation est professionnelle, elle est focalisée et bien plus efficace.

Pour vous donner une idée, chez Gradle, tout le monde est en télétravail.
Mais pour cet aspect "socialisation", nous avons une réunion hebdomadaire, facultative, appelée "coffee time" où chacun peut rejoindre la réunion et parler de sujets extra-professionnels.
Certains en ont besoin, pas moi.
Au contraire, j'aurais du mal à arriver à cette réunion et savoir de quoi parler.
Pire, j'évite au maximum d'arriver en premier à une réunion de peur de ne pas savoir engager une conversation...

Mais encore une fois: parlez moi d'un sujet que je maîtrise, demandez moi d'expliquer un problème, de chercher une solution, d'aider quelqu'un: il n'y aura aucun problème, parce qu'il n'y a aucune place à l'inconnu.
Il est même fort probable que j'apprécie énormément une conversation entre nous: si je ne viens pas vous voir, ça n'est pas que je ne souhaite pas vous parler, c'est que même si je vous connais, engager une conversation reste quelque chose de très compliqué pour moi. Venez me voir, engagez la conversation et tout se passera bien ! :D

Alors, ne vous étonnez pas si je vais trois fois le tour du quartier plutôt que de demander mon chemin.
Ne vous étonnez pas si je ne téléphone jamais, ne texte jamais.

Mais si vous faites partie de mes amis, vous avez énormément de chance: c'est que je tiens beaucoup à vous et vous tiens en haute estime !

## N'ayez pas honte d'être introvertis, faites comprendre ce que c'est

Je terminerais pas une remarque: dans mon https://twitter.com/CedricChampeau/status/1173893698997936130[Tweet original], je disais que je "me soignais".
C'est vrai et c'est faux à la fois.
Quand je dis que c'est vrai, c'est parce que conscient de l'importance et de la "non reconnaissance" de cette difficulté par les autres, j'essaie de travailler, notamment la prise de parole.
Je suis, par exemple, secrétaire du club de Karaté, ce qui me force à communiquer avec des gens que je ne connais pas.
Je suis aussi le coach de l'équipe de basket de mon fils de 10 ans, ce que j'adore faire: c'est une activité avec son enfant, qui est à la fois publique, mais aussi tellement gratifiante, voir ces enfants heureux de jouer, gagner, ... et ça me permet de travailler sur les relations avec les parents !

Et surtout, c'est aussi un message pour mon fils, qui a 10 ans donc mais me ressemble tellement: il a lui aussi beaucoup de mal à parler aux gens, mais je qu'il travaille dur pour se faire accepter. Lui aussi est si fier lorsqu'il a la reconnaissance de ses pairs... Il m'a fallu des années avant de mettre un nom à ce que je suis, un _introverti_, et aujourd'hui encore, je lutte pour ne plus en avoir _honte_.

