= Hello, Mastodon (goodbye Twitter!)
Cédric Champeau
2022-11-06
:jbake-type: post
:jbake-tags: twitter, mastodon
:jbake-status: published
:source-highlighter: pygments
:id: twitter-migration
:linkattrs:

It should be no news to anyone that https://www.bbc.com/news/technology-63402338[Elon Musk finally took control of Twitter].
There were reasons to be worried about this move, but the https://www.reuters.com/technology/twitter-start-layoffs-friday-morning-internal-email-2022-11-04/[recent events at Twitter made it worse than most of us would have thought].

TL/DR: I am moving primarily to Mastodon. You can now follow me at +++<a href="https://mastodon.xyz/@melix">@melix@mastodon.xyz</a>+++.

== Twitter as a self-promotion tool

Lots of people have a complicated story with Twitter, I am no different.
I joined Twitter back in January 2010, and I've grown up to more 4800 followers nowadays, and from time to time, I suffered from being exhausted by the negativity of the network.
Last year, I was even in the middle of an harassment story, because some trolls thought I was someone else.

However, Twitter has been my main communication channel for professional work: this is where I explain what I work on, announce software updates, events I will attend or talk to, or publish blog posts links like this one.
This is also my main feedback channel and where I do most of my technology intelligence.

My community of followers doesn't make me an "influencer" at large scale, like a rock star, but it definitely had an influence on my professional career.
For example, different potential employers explicitly mentioned my "influence" and social media presence, for example, as a major reason why they'd like to work with me.
I have no doubt that without Twitter, my career wouldn't have been the one it is today.
For that, I am forever grateful.

I am also using my Twitter account for personal stuff.
Most notably, some of you have seen my astronomy pictures.
You may also have seen some political posts and point of views being expressed.
While I'm using Twitter professionally, I always made it clear that the opinions I'm expressing are not representative of my employer's point of view.
Said differently, I see my Twitter account as a _tool_, but a tool which "survives" my different employers.
To some extent, it's part of my digital identity.

== Then came Elon Musk

I was already very critical of Elon Musk, and not just because of the infamous Starlink project, for which I have so much to say.
One can admire what he created with Tesla or SpaceX (and I do admire), but at the same time, we can recognize that he's a terrible human being.
This is all about business, all about money, and “freedom of speech” only when it suits his point of view.
Elon is making people work as hard as they can until they burnout or simply get fired once they have "done their job".
Elon is also a "special" view of free speech, where those who pay will have right for free speech, while those who don't won't be visible anymore.
He's also the one blocking anyone criticizing him.

As a consequence, the head of Twitter, and therefore Twitter itself, now represents everything I fight against in my personal life.
This is the world I don't want for my children.
This is the world which puts money before human beings, the world where power, masculinity, is emphasized.
Elon doesn't care that we exhaust resources, as long as part of the population can survive, be it on Mars (!).

But now, he fired half of the company, by email, https://techcrunch.com/2022/11/04/twitter-faces-a-class-action-lawsuit-over-mass-employee-layoffs-with-proper-legal-notice/[ignoring the law], because, you know, Musk does whatever he wants.
It happens that I know people who got fired and I also know folks who used to work for Twitter before.
I, for one, am respectful of what people produce.
I am respectful of what efforts it takes to build a site like Twitter, and, in general, I am someone who puts _trust_ in other people at the top of my hierarchy of beliefs.
So I find it extremely annoying, or, to be clear, disgusting when someone who has absolutely no understanding of how to build such a large community over the years, decides to layoff half of a company, change the spirit of the website so that paying customers have more power than the others, so that it matches more his political point of view.
Even if the company is losing $4M a day, compared to B44$, seriously, what would have it taken to show the people who built Twitter a bit of respect and simply build a plan, say, of volunteer departures.

Elon Musk's behavior is everything I hate: someone coming because they have power (understand, money), and then ruining other people lives just because he can, without any respect.

This puts me in a difficult situation: at the same time, I _need_ Twitter, because it's a professional tool which can't be easily replaced and I _have to go_ because there's no way I'm going to pay 8 dollars a month to a company who treats human beings like that, and simply to get more visibility over others just because I can afford it.

== Hello, Mastodon!

As a FOSS supporter, back in 2017, I had registered to https://joinmastodon.org[Mastodon].
My account was left more or less inactive for years, because, honestly, not many people used it so it was ... annoying.
This was like talking in an echo chamber.
Until the rumor of Elon Musk acquiring Twitter started: we've seen more and more people joining, and I'm super glad that this week alone, _many_ other people, including from the Tech industry, decided to make the move.

No more ads. No more recommendations. A clean timeline, as it should be.

It's really refreshing to be on Mastodon, it feels like the Twitter from the early days.

However, Mastodon has a number of key differences, which make it more "complicated" for users to understand.
First of all, and that's the biggest issue for joining, Mastodon is _not_ a single site like Twitter: it's a _federation_ of servers.
Just like you have a provider for your email (say GMail, Hotmail, etc.), you can choose your Mastodon server provider.
As an OSS project, you can go even as far as hosting your own instance.

Therefore, Mastodon is, by nature, distributed, which makes it completely immune to what just happened to Twitter.
But it also means that there are a few things you should be aware when you join a server:

- content moderation is the responsibility of the server administrator: they can block you, read your posts, private messages. They can block other providers too, which means, for example, that if you choose to go to an instance which has a Code of Conduct, you have to follow the rules.
- the good news is that you _own the content_: if you are not happy with your server moderation rules, you can _move to a different instance_, and you can move your data with it: toots, folks you follow, followers, ...
- the cost of maintenance is distributed on the community: there are lots of _free_ servers out there, but you can choose to participate to the bills. You can even build your own server, for a price which wouldn't exceed much what Elon wants us to pay to get a blue mark
- Hashtags are much more important in Mastodon than Twitter: there's no _global search_: the only things which are indexed are hash tags. You won't find contents which is not with a hash tag.

This is the internet I remember of.
It's not suitable for everyone, but it's what I call _open_.
What I also like is that it respects freedom of speech, while preserving your freedom of not seeing assholes (there are instances which are full of alt-right folks, but at least, we can block the whole server and not have to suffer their nauseating posts).

== Conclusion

So, for the time being, I'm transitioning to Mastodon.
**You can follow me at +++<a href="https://mastodon.xyz/@melix">@melix@mastodon.xyz</a>+++**, and I strongly suggest that you do the same and find a server which suits you.
I will _not_ support a company which now represents the worst of human beings.
I will _not_ pay $8 a month to a company which shows no respect to its employees, content creators and business partners.

Because it's hard to say goodbye to a professional network just like that, I do not plan to shutdown my account on Twitter yet, though: I still didn't find a way to solve this cognitive dissonance.

So what I plan on doing is moving to Mastodon first.
I have already updated my screen name in Twitter to give a link to my Mastodon account.
I suggest you do the same.
I will now limit my tweets to what is strictly required for my professional career (announcements, etc.).
I will also mostly answer to tweets which are related to moving to Mastodon and use Mastodon for everything else, until I can completely get rid of Twitter.
I am conscious that I may not be able to completely get rid of it, if too many people stay on Twitter.
So be it.

Congratulations M. Musk, you ruined Twitter!

