= Je suis le gars chiant
Cédric Champeau
2022-07-28
:jbake-type: post
:jbake-tags: science, naturopathie, homéopathie, biais cognitifs, zététique
:jbake-status: published
:source-highlighter: pygments
:id: je-suis-le-gars-chiant
:linkattrs:

La science. Si j'avais eu les capacités pour comprendre les abstractions mathématiques nécessaires (j'essaie encore, de temps en temps), je serais, peut-être, aujourd'hui assis dans un laboratoire de recherche en astrophysique. J'ai toujours trouvé fascinant la capacité à émettre des hypothèses, puis les vérifier expérimentalement, pour en faire des théories, théories qui, constamment, peuvent être remises en cause lorsque de nouvelles observations les contredisent. Je suis assis derrière un bureau, mais dans le développement informatique. Ma passion, mon loisir, c'est l'astronomie.

=== Alors oui, mais non

J'ai grandi dans un monde empli de graphologie, de magnétisme, d'ufologie, de pyramidologie, d'expériences de mort imminente, qui m'ont aussi profondément marqué. J'ai entendu des témoignages, j'ai constaté des guérisons, j'ai _cru_ à des beaucoup de choses. Mais pendant une grande partie de mon enfance, je n'avais pas le bagage intellectuel suffisant pour _comprendre_. En un mot, ma fascination pour les sciences se mélait allègrement à celle pour les pseudo-sciences. Parce que j'ai toujours cherché des explications, j'en suis revenu et je pense que cette expérience a renforcé mon sens critique si tant est que je me sens, de nos jours, extrêmement proche du mouvement https://fr.wikipedia.org/wiki/Z%C3%A9t%C3%A9tique[zététique] et combats fermement l'anti-science.

En soirée, je suis le gars chiant qui ne supporte pas qu'on introduise du surnaturel là où il existe des explications rationnelles, celui qui soulève un sourcil amusé lorsqu'on lui parle de https://fr.wikipedia.org/wiki/S%C5%93urs_Fox[séances de spiritisme].

Celui qui vous explique que https://www.lequotidiendumedecin.fr/archives/pr-edzard-ernst-si-lhomeopathie-est-presentee-comme-une-panacee-il-faudra-quelle-prouve-son[l'homéopathie ne fonctionne pas] et qui vous rappelle que s'il https://www.monvoisin.xyz/wp-content/uploads/2020/07/Monvoisin-Pinsault-Diplo-avril19_p21.pdf[existe un effet placébo, il est moralement discutable de le rembourser].

Je suis le gars chiant qui, il y a déja des années, avertissait mes amis sur la montée du https://www.ladn.eu/nouveaux-usages/antivax-histoire-mouvement/[mouvement antivax].
Je suis le gars chiant qui, en tant qu'astronome amateur, vous démontre que https://www.afis.org/L-astrologie-a-l-epreuve-ca-ne-marche-pas-ca-n-a-jamais-marche[l'astrologie n'a aucun sens].
Je suis le gars chiant qui s'indigne qu'on puisse vous vendre des absurdités comme des colliers en ambre pour les douleurs dentaires des bébés ou des https://menace-theoriste.fr/lithotherapie-1/[pierres à recharger sous la lumière de la lune].

Je suis le gars chiant qui vous invite à douter de la médecine chinoise, responsable du https://dragondubled.fr/medecine-chinoise/rhinoceros-medecine-chinoise/[massacre des rhinocéros] et de la https://fr.wikipedia.org/wiki/Bile_d%27ours[maltraitance d'ours] pour des produits dont il est démontré qu'il n'ont aucun effet.
Je suis le gars chiant qui, lorsqu'on lui parle de produits naturels, vous rappelle que https://fr.wikipedia.org/wiki/Appel_%C3%A0_la_nature[naturel ne veut pas nécessairement dire bon pour la santé].
Je suis le gars chiant qui vous explique que si les électrosensibles sont réellement malades, https://www.contrepoints.org/2021/11/22/227498-electrosensibilite-la-maladie-imaginaire-du-xxieme-siecle[ça n'est pas à cause des ondes mais de mécanismes psychologiques proches des phobies].
Je suis le gars chiant qui s'insurge contre https://www.radiofrance.fr/franceinter/podcasts/antidote/antidote-du-vendredi-22-octobre-2021-5726804[la naturopathie et ses tendances complotistes] et invite à prendre connaissance https://www.la-croix.com/Famille/Ecole-meditation-pleine-conscience-accusee-derive-sectaire-2022-02-14-1201200267[des dérives sectaires de la méditation pleine conscience].

Je suis le gars chiant qui se dit écolo, mais aussi pro-nucléaire: je suis effondré lorsque les https://www.latribune.fr/economie/union-europeenne/l-allemagne-pourrait-prolonger-des-centrales-a-charbon-pour-reduire-sa-dependance-au-gaz-russe-906817.html[écolos incitent à relancer des centrales à charbon] alors que https://bonpote.com/nouveau-rapport-du-giec-agir-coutera-moins-cher-que-le-business-as-usual/[les rapports du GIEC nous disent que chaque tonne de CO2 compte].
Je suis le gars chiant qui choque ses amis écolos lorsqu'il affirme que https://doseequivalentbanana.home.blog/2021/05/08/dechets-8-on-ne-sait-pas-gerer-les-dechets-nucleaires/[le stockage géologique des déchets nucléaire n'est pas un problème pour les générations futures]. 

Je me sens écologiste et je suis convaincu que nous devons aller vers la sobriété: je recherche des modes de vie alternatifs, moins impactants pour l'environnement, moins industriels et à ce titre j'ai été attiré par les concepts des https://fr.wikipedia.org/wiki/Mouvement_Colibris[colibris] et ses nombreuses variantes.
Mais je vérifie, je confronte mes croyances. Je suis le gars chiant qui découvre que presque tous les mouvements écologistes sont infiltrés par des groupes anti-science, au premier rang desquels on trouve la https://blogs.mediapart.fr/mathieu-repiquet/blog/090520/qu-est-ce-que-l-anthroposophie-entretien-avec-gregoire-perra[secte anthroposophique]. Je suis le gars chiant qui vous fait remarquer que https://www.reussir.fr/ce-celebre-youtubeur-radicalement-change-sa-vision-de-lagriculture[la permaculture ne permet pas d'être auto-suffisant], que la plupart de ces mouvements dits alternatifs ne survivent que grâce à des "formations" qui s'auto-entretiennent et/ou financent des sectes.

Je suis l'écolo qui vous déculpabilise de ne pas https://www.youtube.com/watch?v=rtG77t9kshE[effacer vos emails car celà ne réduira pas votre emprunte carbone], mais en profite pour vous faire remarquer que ne pas utiliser votre sèche-linge, oui.

Je suis le gars chiant qui s'inquiète lorsque des proches suivent des formations de développement personnel ou aux https://fr.wikipedia.org/wiki/Enn%C3%A9agramme[ennéagrammes], parce qu'il cherche https://www.unadfi.org/actualites/domaines-dinfiltration/sante-et-bien-etre/psychotherapie-et-developpement-personnel/alerte-sur-les-formations-a-l-enneagramme/[qui sont ceux derrière ces mouvements] et se rend compte qu'il est très facile de tomber dans des dérives sectaires et ne pas s'en rendre compte.

Je suis aussi le gars chiant qui fait confiance aux autorités sanitaires, y compris quand elles concluent qu'https://france3-regions.francetvinfo.fr/pays-de-la-loire/loire-atlantique/nantes/cancers-pediatriques-du-pays-de-retz-retour-sur-six-annees-de-combat-1990363.html[il n'y a statistiquement pas de surnombre de cancers pédiatriques au Sud de Nantes] alors qu'on était en https://www.ouest-france.fr/pays-de-la-loire/sainte-pazanne-44680/cancers-pediatriques-un-22-sup-e-sup-cas-confirme-autour-de-sainte-pazanne-da95a8e2-f7fc-11ea-86be-f690571173ca[droit de s'inquiéter], mais aussi prêt à revoir ma position si de nouvelles données étaient disponibles.

Je suis celui qui heurte la sensibilité de ses amis, les choque, les énerve parfois (souvent), parce que j'apparais comme ne croyant en rien.

=== Triste vie que celle de celui qui ne croît en rien

Est-ce vrai ? Est-ce que je ne crois réellement en rien ? 
Bien évidemment non. 
J'ai mes propres croyances. 
Par exemple, je _crois_ qu'il existe une vie extra-terrestre. Sous quelle forme, je n'en sais rien, mais j'en suis intimement convaincu. Mais il s'agit d'une croyance, et en tant que tel, je n'essaierai pas de vous l'imposer. Je peux vous donner des idées sur le _pourquoi_ j'y crois, mais il n'existe aucune _preuve_.
J'ai cru à beaucoup de choses aussi: gamin j'ai cru au bisou magique, j'ai cru au Père Noël, j'ai cru que la graphologie fonctionnait (alors que je suis horrifié de constater que cet outil est toujours utilisé de nos jours !).
Je crois qu'il n'existe pas de vie après la mort, mais je ne peux pas vous en apporter la preuve.
Je crois aussi qu'on n'a pas besoin de revenir 200 ans en arrière en agriculture pour "sauver la planète".

Alors on pourrait dire "mais c'est pas bien grave", "mais les plantes c'est quand même bien, c'est mieux que les produits chimiques", "la science n'explique pas tout", "faut il se fâcher pour ça ?".
Tant de lieux communs, qui n'apportent rien, mais qui, en revanche, cachent de tristes réalités: https://www.leparisien.fr/faits-divers/miguel-b-le-naturopathe-qui-pretend-guerir-le-cancer-aurait-fait-au-moins-deux-autres-victimes-14-10-2021-XMQKFRJHGFFDLJQRZZ4DWW4E5E.php[des morts], souvent https://www.midilibre.fr/2021/11/23/covid-19-quest-ce-que-lanthroposophie-possible-frein-a-la-vaccination-dans-les-pays-germanophones-9945410.php[par milliers].

=== Dur d'être celui qui gâche la fête

Alors je si je suis suis le gars chiant, je ne cache pas que c'est parfois fatigant, moralement: si j'écris ce billet, c'est aussi pour exprimer cette fatigue.
C'est fatigant parce que je vais contre les idées reçues, je "casse l'ambiance" mais surtout je peux me fâcher avec des personnes que j'apprécie énormément.
C'est fatigant parce qu'on me regarde en sachant d'avance que je vais intervenir, mais on ne croira pas ce que je dis, même preuves à l'appui.
C'est fatigant parce que je constate la montée de l'obscurantisme, du complotisme et que je me sens impuissant.
C'est fatigant parce qu'il est urgent d'agir pour sauver notre avenir (je ne parlerai pas de sauver la planète, c'est l'espèce humaine, et les espèces actuelles en général qui est en jeu) et que les décisions prises ne sont pas à la hauteur.
C'est fatigant parce que j'aspire à plus d'écologie, plus de simplicité, mais que tous les mouvements que je trouve sont plombés par de l'anti-science et des sectes déguisées en "spiritualité".
C'est fatigant parce qu'on me caricature: je suis le "rationnel" qui ne comprend rien aux sciences humaines ou à l'humain en général.
C'est fatigant parce qu'on se bat constamment contre l'intolérance.
Tout ce que je vous raconte est présent partout: famille, amis, collègues, politiques, mais chez moi y compris.

Alors, parfois, parce que je ne veux pas me fâcher ou faire honte à madame, je me tais et je deviens d'humeur sombre, ne m'en voulez pas.

Nous sommes tous pleins de croyances: la question est de savoir si nous sommes prêts à les remettre en question, pour le bien de tous, et si ces croyances doivent influencer les décisions que nous prenons pour la communauté.
Et parce que nous sommes tous susceptibles de faire des erreurs, je ne porte aucun jugement moral à celles et ceux qui croient ceci ou celà: nous sommes tous pleins de contradictions et je ne suis pas mieux qu'un autre.
Je n'en veux pas à ceux qui croient, je ne doute pas qu'ils aient de bonnes intentions.
Je pourrais en vouloir à ceux qui continuent de croire lorsqu'on leur montre qu'il y a de quoi douter, ou mieux qu'on leur apporte des preuves, mais https://fr.wikipedia.org/wiki/Biais_cognitif[notre cerveau est câblé pour rendre la remise en question difficile].
J'en veux, en revanche, à ceux qui utilisent _sciemment_ l'ignorance des gens pour en tirer profit financièrement ou pour psychologiquement de personnes.

Je n'ai pas de chiffres à vous donner, mais _je crois_ que ces ordures sont nombreuses.


