= [Update] Adobe releases a buggy flash plugin once again
Cédric Champeau
2008-10-15
:jbake-type: post
:jbake-tags: flash, flex, linux
:jbake-status: published
:source-highlighter: prettify
:id: adobe_releases_a_buggy_flash

Today more than ever, I’m really angry about Adobe. They have just released a brand new Flash 10 plugin with a very annoying bug which is there for months : Adobe hates Linux users, especially non-US users. Would anyone tolerate that a Windows user can’t write text in its favorite editor ? No, because if you’re not able to input text, you are not able to do anything with your computer. It’s just what’s happening with this Linux release once again : special characters (unicode) like accents, @, \{, … can’t be entered.

The bug has been reported *https://bugs.adobe.com/jira/browse/FP-40[in early April this year]* AND IT’S STILL NOT FIXED ! Furthermore, no one at Adobe deigns to answer. Adobe ignores 39 votes, placed 10th most voted in the bug tracker. You’ll also notice that the most voted is another Linux issue.

It’s really a pity that Adobe does not wish to take Linux users seriously. It just makes impossible to release Flex based applications for customers which use Linux. More, it makes our work harder since, like me, many developers develop on this platform.

*Update* : I had a https://www.jroller.com/melix/entry/adobe_releases_a_buggy_flash#comments[comment from Adobe] this morning, saying they are working on the issue. I hope this is good news for us, and that I’ll be able to reconsider my opinion soon.
