= Looking for a new job
Cédric Champeau
2015-01-19
:jbake-type: post
:jbake-tags: groovy,jvm,job
:jbake-status: published
:source-highlighter: prettify
:id: for_hire
:groovylang: https://beta.groovy-lang.org
:icons: font

== Will you be the new Groovy sponsor?

There we are. January 19th was a bad day as Pivotal https://blog.pivotal.io/pivotal/news-2/groovy-2-4-and-grails-3-0-to-be-last-major-releases-under-pivotal-sponsorship[announced that they wouldn't sponsor the development of the Groovy language], as well as its long time friend the Grails framework, starting from march 31st. As I was paid to work on Groovy, it has a direct consequence for me: starting from April 1st, I am *for hire*. For you, it probably doesn't change much as Groovy and Grails existed before Pivotal without corporate funding.

It was hard to keep this secret for weeks, but now that everything is public, it is easier for us. I have been lucky to work full time on the Groovy language for a bit more than 3 years now. Lucky because it was both a great open-source software and my passion. I have implemented major features of the language https://github.com/groovy/groovy-core/graphs/contributors[since Groovy 1.8]: static type checking, static compilation, Android support, numerous AST transformations, continous integration... I have given talks to various conferences, including world class ones like JavaOne, Devoxx, GR8Conf or SpringOne2GX and it was a fantastic opportunity that wouldn't have been possible without the support from VMware then Pivotal. 

However I feel that *I still have a lot to do*. So many things are on the list, so much to improve, like for example adding language support for asynchronous programming, improved Java 8 support, a new meta-object protocol, not forgetting, of course, bugfixes... I am 100% convinced that the language wouldn't have reached the level of maturity it has without support from a company like Pivotal. And even though Java is considered mature, it doesn't mean that the language shouldn't continue to evolve: it is rather the opposite. People are constantly asking for evolutions, because programming models evolve too.

For those reasons, my #1 choice would be to find a new company securing the development of Groovy and Grails, that is to say willing to pay me and my mates to continue working on them. The Groovy community is huge, there are lots of companies using Groovy in a variety of domains, I sincerely hope this is possible. With more than 4 million downloads in 2014, I can't imagine how many hours of development have been saved thanks to Groovy and Grails... Should you be interested in sponsoring our projects, please write to sponsorship@groovy-lang.org.

== About me

If unfortunately we can't find third parties willing to take over the development of the language and hire us, then I would obviously be available to help you in your projects. For those of you who are looking for someone with a good knowledge of the JVM internals, I am listening. My areas of interest:

- *R&D*: innovation, technical challenges are what drive my motivation
- *open-source* over closed-source: If you are an Open-Source company, by that I mean a company which contributes Open-Source, I think we are on the same line. I love to share what I do and I am convinced that open-source development is the best way to improve the global quality of a project. I have worked on closed-source software in the past, there are good reasons to do so but working on OSS software is really what I prefer. I also enjoy https://speakerdeck.com/melix/[speaking publicly] about projects I work on.
- *JVM*: I have spent most of my career on that platform and believe me, it's not dead :)
- *back-end* over front-end: I love working on tooling, performance tuning, algorithmics... everything that is hidden to the end user. On the other side I am not so good on the front-end part (HTML, CSS, ...) so it would probably not be a good idea to make me work on that topic :)
- *remote working*: I live in Saint Hilaire de Loulay, a small countryside town near Nantes, in France. I have now been working from home for more that 3 years, most of the Spring Framework team works that way, and it has been very successful so far. If you are not against the idea, I would love to continue that way.

In any case if you think a profile like mine is interesting for your company, you can contact me or ask for my résumé at cedric.champeau@gmail.com. Meanwhile, rest assured that we are focused and we will soon release Groovy 2.4 to prove that!
