= JLangDetect 0.4 released and moved to GitHub
Cédric Champeau
2014-01-22
:jbake-type: post
:jbake-tags: detection, europarl, java, jlangdetect, language, nlp, github
:jbake-status: published
:source-highlighter: prettify
:id: jlangdetect_0_4_github

== A new era

Back in 2011, I initiated a project called `JLangDetect`, a language detection library for the JVM. At that time, I was working for
a company that made NLP tools and I started this as a pet project on my free time. I made it available as open source software and
people started to use it, so I was pretty happy at that time to see a project I initiated being actually used in production!

While I don't have the need for such a library now that I work on the Groovy language, some people are still using it. At the first
place, a friend of mine, Freddy Rabiller, took time to upgrade it. A new version has been released (0.4) and the project is now
available on https://github.com/melix/jlangdetect[GitHub].

A big thank to Freddy, who will probably take the lead of development on this project now!


