= Parlons Gradle : Episode 1
Cédric Champeau
2017-10-30
:jbake-type: post
:jbake-tags: gradle,meetup,online
:jbake-status: published
:source-highlighter: prettify
:id: parlons-gradle-1

Suite à de nombreuses discussions via Twitter, j'ai souhaité organiser des discussions en ligne pour que nous puissions parler de Gradle. Le premier épisode aura lieu mercredi prochain, notez la date !

++++
<div style="text-align:center; color:red; font-size: 2em">
++++

**LE MERCREDI 6 DECEMBRE , à 17h GMT+1 (Paris)**

++++
</div>
++++

La rencontre se fera via Google Hangouts. Si vous êtes intéressés, envoyez-moi un mail (cedric -at- gradle -point- com) ou un https://twitter.com/CedricChampeau[tweet] avec votre email pour que je vous envoie une invitation. Pour des raisons pratiques, elle se fera en français uniquement !

== De quoi va-t-on parler ?

L'objectif pour moi est de récolter votre ressenti sur Gradle, son utilisation, vos problèmes au quotidien, la documentation, les exemples, mais aussi ce que vous aimez, votre utilisation, ... Bref, votre expérience utilisateur. Certains sont encore convaincus que Maven est supérieur, ce qui, de mon point de vue, reste un mystère, et j'ai donc besoin d'entendre votre feedback pour savoir comment corriger (si nous n'avons pas encore entrepris de démarche dans ce sens).

Bref, il s'agira d'une discussion ouverte, d'environ 1h. Bien entendu nous pourrons parler du futur de Gradle si nous avons le temps.

Au plaisir de vous voir !

