= Assistants vocaux et robotisation: mon point de vue
Cédric Champeau
2018-07-03
:jbake-type: post
:jbake-tags: google home,alexa,robotisation
:jbake-status: published
:source-highlighter: prettify
:id: robotisation


Ce billet essaie de résumer une conversation que j'ai eu avec mon frère, concernant les craintes autour des assistants vocaux, et, plus généralement, la robotisation. Je partage une grande partie de https://www.blogdumoderateur.com/role-controverse-assistants-vocaux/[son point de vue], mais j'ai aussi de larges différences que je voulais résumer ici. C'est parti !

= "Ok Google, crée un malaise"

Le week-end dernier, à l'occasion d'un barbecue en famille à la maison, ma moitié a, au détour d'une conversation, lancé cette phrase par pur réflexe:

"Ok Google, <question anodine>"

Là, mon frère, Guillaume, a fait un malaise. Etendu sur le sol, pris de spasmes incontrôlables, en position foetale, il baffouillait des phrases pour la plupart inintelligibles, mais, par moments, j'arrivais à comprendre des bribes comme "pas eux", "GDPR", ou autres "Saint Qwant venez-vous en aide". Après quelques minutes, l'intervention d'un seau d'eau et rongé par la honte de se montrer ainsi devant junior, Guillaume repris ses esprits, et commença une discussion trop courte parce qu'interrompue par la nécessité autrement plus primaire de faire griller quelques saucisses.

Au final, la question se résume à celle-ci: pourquoi ? De mon côté, je suis assez ouvert sur l'utilisation des assistants, et je dois dire que c'est quelque chose que j'attendais véritablement depuis des années. De lonnngggues années. Guillaume n'avait probablement rien noté jusqu'ici parce que mon assistant prenait la forme d'une enceinte bluetooth classique, alors qu'il s'agit en fait une enceinte Sony intégrant la technologie de Google. J'avais choisi ce modèle principalement parce qu'une des utilisations que je fais de cet assistant, probablement la plus fréquente, est de lui demander de me diffuser de la musique (via Deezer), ou la radio. La domotique, c'est un peu un rêve de gosse pour moi, j'adore tout piloter, par une appli, ou par la voix. Donc parmi les autres utilisations que j'en fais, il y a:

- contrôler mes lumières, mon thermostat
- contrôler ma box domotique (et donc les appareils non directement "connectés")
- demander des informations (météo, à quelle heure est le match de la France, ...)
- enclencher un minuteur pour la cuisine, ajouter des rappels

Le problème, qui choque Guillaume, est que pour avoir accès à toutes ces fonctions, je partage énormément de données avec El Diablo (Google). Oui, mais j'en suis conscient. Et, par ailleurs, mon compte est configuré avec une extrême précaution. Notamment, j'ai complètement désactivé la personnalisation des annonces. Je garde néanmoins certaines fonctionnalités comme le traçage de ma position géographique (qui, par une occasion, m'a permis de démontrer à des amis qu'on était bien allé les voir au mois d'Octobre :)). J'ai plus de mal, en revanche, sur l'historique des recherches. Mais le noeud du problème, c'est qui détient les données, ce qu'ils en font et en particulier avec qui ils les partagent. Pour ma part, la seule raison pour laquelle j'utilise les services de Google est qu'ils me permettent _techniquement_ de faire ce que je veux. Si, demain, j'ai la possibilité d'avoir une box locale qui m'offre les mêmes capacités, y compris lorsqu'invoquée via IFTTT, je signe à quatre mains. En attendant que celà existe, et j'espère sincèrement que celà arrivera au plus vite, je fais des compromis, et il faut être conscient de ce que l'on a a la maison.

Là où je suis moins d'accord, c'est la diabolisation à l'extrême des assistants. Je reviendrais plus tard sur quelques raisons, mais en particulier un argument que j'entends souvent, c'est "oui mais là tu as un micro qui écoute tout le temps chez toi et qui envoie tes données à Google". Ah, nous y voilà. Quel est le problème ?

1. ça écoute tout le temps ?
2. ça envoie tes données ?
3. ça les envoie à Google ?
4. qui traite des infos ?

= Intention malicieuse ou non ?

J'avoue que j'ai du mal à comprendre les réticences ici. Probablement parce que je suis un développeur naif, mais les bugs, les amis, je suis désolé de vous l'apprendre, il y en aura toujours. Donc, oui, il arrivera que votre Google Home, votre Amazon Alexa ou autre, se mette à enregistrer une conversation qu'il n'aurait pas du, et l'envoie sur les serveurs de Google. En règle générale, on le comprend assez vite, parce que la douce voix robotique vous répondra quelque chose du genre "désolé, je ne sais pas comment vous aider". Que s'est-il vraiment passé ? La box a cru entendre un mot clé. Souvent, on se demande parfois pourquoi Google n'offre pas la possibilité de changer ce mot clé ("Ok Google", "hey Google", ...). Je pense qu'une des raisons est ce que l'interprétation de ce mot clé est forcément locale. La puissance nécessaire pour reconnaitre parfaitement l'expression, et son contexte de déclenchement avec le bruit, est restreinte. Donc, parfois, pas de bol, ça croit entendre "Ok Google", ou, pire, ça s'enclenche lorsque la pub passe à la télé. En règle générale, ça fait plutôt rire mes enfants, rien de dramatique. D'autant qu'on sait que ça s'enclenche grâce au signal sonore "attention, Google écoute". Donc, un bug, c'est un bug. Ca n'est pas parce que ça _peut_ envoyer des données sans votre accord que l'intention derrière est malicieuse. Dois-je vous rappeler les histoires d'activation à distance des webcams des Mac Book par la NSA ? On n'est pas dans la même catégorie, là. Enfin, des micros qui écoutent tout le temps, vous en avez en poche depuis des années: vos téléphones mobiles. Ils font exactement la même chose, sont activables à distance, et probablement infectés de tonnes de malwares, parfois installées en usine, à des fins d'espionnage gouvernemental. Si je dois me méfier de quelque chose, personnelement, c'est plus de ça que de Google recevant ma discussion sur tata Simone.

Par ailleurs, une fois la conversation envoyée sur le "cloud" (ça fait peur, le cloud, on ne sait pas ce qui s'y passe), elle est analysée. Pensez-vous que ce sont des humains qui analysent votre question et renvoie la réponse en 2s ? Non, la puissance de calcul nécessaire pour interpréter correctement votre question et titanesque. Elle nécessite des techniques avancées (TALN, statistiques, oui, vous savez, la même chose que ce gros mot "big data"), et l'apprentissage pour l'amélioration de la qualité des réponses requiert le stockage de quantités monstrueuses d'information. Je ne suis pas convaincu que Google doive pour autant _stocker_ toutes les conversations, mais je conçois parfaitement qu'en analysant les requêtes de millions d'utilisateurs, avec des voix différentes, des accents différents et des contextes culturels différents, on est capable de faire beaucoup mieux qu'en ne stockant rien et analysant localement. Le temps où il fallait patiemment passer des heures à répéter des tonnes de phrases à son logiciel de reconnaissance vocal n'est pas si loin...

Donc, oui, Google va recevoir ma voix. Oui, il va l'analyser et construire un profil, qu'il pourra partager. Je suis au courant. Et j'ai, dans la mesure du possible, restreint ces possibilités. Je serai d'autant plus heureux le jour où je n'aurai pas besoin de lui confier mes données. Mais l'intégration, la simpliciter d'utilisation, et le seul fait que ça marche, aujourd'hui, est la raison de son adoption. Enfin, on dit que ça marche, mais après des mois d'utilisation, il ne faut pas très longtemps pour comprendre que malgré les quantités énormes de données dont Google dispose, dans de très nombreux cas, l'assistant est complètement à la ramasse. Genre, on lui demande si un match passe sur TF1, il est incapable de répondre. On lui demande "quel temps va-t-il faire", il comprend "température". On apprend même à reformuler nos questions pour que l'assistant les comprenne. Bizarre, et frustrant. Mais, ça montre les limite de la technologie, et casse quelques mythes. En particulier, il faut se méfier des annonces autour de Google Duplex, l'assistant qui prend des rendez-vous à votre place: oui, ça marche, c'est bluffant, mais il est conçu pour cette tâche spécifique, et il est finalement assez simple, d'après les premiers retours, de lui faire perdre le fil.

= La relation homme-machine

Néanmoins, la conversation a dévié vers l'intelligence artificielle en règle générale, et la relation qu'on a avec les machines. Sur ce sujet, je suis _extrêmement_ ouvert. Je suis très introverti, et, personnellement, avoir une conversation avec une machine a un côté rassurant. Me demandez pas pourquoi, c'est un fait. Je narrais aussi cette anecdote à mon frère: un de mes enfants a des difficultés à parler aux adultes. Il marmonne, ne les regarde pas dans les yeux, et met _beaucoup_ de temps à leur accorder sa confiance (mais une fois qu'elle est acquise, il n'y a plus de pb). Personnellement, ça ne m'a jamais inquiété, j'étais pareil enfant, et ça n'a (je pense) pas fait de moi un être associal (j'espère). Disposant de Google Home, mon fils s'est naturellement mis à l'utiliser lui aussi. Et ses premières expériences étaient frustrantes: n'articulant pas, la machine n'était pas capable de le comprendre. En quelques semaines seulement, il a progressé plus qu'en plusieurs années: désormais, il articule et parle fort, y compris aux adultes (à de rares exceptions près pour ceux qui l'impressionnent comme le médecin). Ce sujet en a apporté un autre: celui du fait de faire dire aux enfants "merci" ou "s'il te plait" aux machines.

Guillaume est, si j'ai bien compris, contre l'humanisation des machines. Pour ma part, j'y suis favorable, et je suis donc pour la "politesse envers les machines". Fondamentalement, je pense qu'une partie des craintes de Guillaume se fondent sur le fait de confier l'empathie aux machines et que des algorithmes s'en servent pour nous manipuler. L'autre aspect est l'aliénation de l'homme à la machine, c'est à dire apprendre à des enfants à obéir non plus à des hommes mais à des machines. Soit, c'est une crainte légitime. Je suis plus cynique que celà: je doute qu'une machine puisse faire pire qu'un être humain. En fait, j'ai plus d'espoir envers les machines que je n'en ai envers les êtres humains. L'histoire a montré a de trop nombreuses occasions que l'empathie n'est pas l'apparat de tout le monde, bien au contraire. L'utilisation des biais cognitifs à des fins de manipulation (vente, politique, abus de confiance), ça n'a rien de nouveau. Est-ce qu'il faut craindre que les algorithmes fassent de même ? Oui. Serait-ce pire qu'avec des humains ? J'en doute, bien au contraire. L'imagination perverse des hommes n'est plus à démontrer. Leur intolérance non plus.

= Suis-je humain ?

J'ai grandi avec Star Trek. 

Cette série est probablement celle qui a influencé une grande partie de ma pensée. Déja dans Star Trek TOS, l'ordinateur et la domotique étaient au coeur de la relation homme-machine. La machine était naturellement intégrée, un personnage "vivant" en quelque sorte. Puis, arriva Star Trek The Next Generation, avec des personnages encore plus humanistes, mais un personnage en particulier, Data, change la donne: un Androide dont la seule quête était de devenir humain. Un membre à part entière de l'équipage. Un https://en.wikipedia.org/wiki/The_Measure_of_a_Man_%28Star_Trek:_The_Next_Generation%29[épisode en particulier traite spécifiquement du sujet du droit des robots]: Data devait-il être considéré comme une machine ou un humain ? Un scientifique a-t-il le droit de le démembrer pour l'étudier sur le seul prétexte qu'il s'agit d'une machine ?

J'adore cette série pour celà: son humanisme, sa capacité à rechercher ce qu'il y a de meilleur chez l'homme, et son ouverture en général. Subtilement mais sûrement, les sujets sensibles sur le racisme, le transhumanisme, l'homosexualité y sont traités. 

Je fais donc partie de ceux qui préfèrent avoir une "conversation" avec une machine polie, lui répondre "merci", tout en sachant qu'il ne s'agit que d'une machine, plutôt de de causer à un con... raciste, homophobe, ou plus fréquemment un télécommercial essayant toutes les techniques possibles pour me vendre ses panneaux solaires sachant pertinnement que je veux terminer ma conversation avec lui. Je pense que la politesse, le "savoir vivre", procure une certaine satisfaction, une relaxation, qui est un concept totallement orthogonal avec le sujet (l'homme ou la machine). Il n'est pas surprenant pour moi que des autistes s'ouvrent plus facilement avec la présence d'un animal (chien, chat, peu importe), ou que certaines expériences montrent des enfants https://www.topsante.com/medecine/psycho/autisme/des-robots-une-aide-pour-les-enfants-autistes-63967[faisant des progrès en parlant à des robots]. L'interaction, la socialisation est importante. Et si le robot est meilleur que l'homme sur ce sujet, on doit s'en réjouir ! L'homme a toujours cherché à créer des choses à son image (ça ne vous rapelle rien ?) et il se trouve que notre cerveau est conçu pour reconnaitre la douleur de l'autre (empathie) et y réagir. Je préfère donc 100 fois, que dis-je, 1000 fois un homme poli envers un robot, qu'un homme traitant une autre personne comme une machine. C'est peut-être naif, mais j'ai espoir qu'en apprenant à des enfants à être polis envers des machines, ils apprendront d'autant plus à l'être envers les autres, et qu'on effacera une partie de ce mal, qui est la disparition à l'échelle de la société de l'empathie. Et mon rêve de gosse, c'est de voir un Data émerger. Montrer qu'avec suffisamment de puissance, une machine puisse prendre son autonomie. On en est encore loin, mais, on réduit déja ce qui est "visible" entre homme et machine. Si je ne suis pas capable de faire la différence entre un homme et une machine dans une conversation, qu'est-ce que celà dit de moi ? Qu'est-ce que celà dit de la machine ? Et si, nous mêmes, n'étions finalement qu'une machine un peu sophistiquée, issue de l'évolution. Une machine douée de pensée et de sentiments, mais une machine quand même.

