= Chronicles of an introvert remote worker
Cédric Champeau
2020-01-03
:jbake-type: post
:jbake-tags: remote work, introversion
:jbake-status: published
:source-highlighter: pygments
:id: introvert-remote-en-pub
:linkattrs:

[NOTE]
====
This post is the translation in English of the most popular blog post I wrote in October, 2019, which was originally posted in french.
Lots of folks commented they found it useful and that they recognized themselves in the description so I decided to translate it to English.
====

The other day I was listening to https://lescastcodeurs.com/2019/09/16/lcc-216-l-episode-ou-on-a-perdu-le-compte/[Les Cast Codeurs podcast] which mentioned the topic of remote working.
 
Some comments made me raise an eyebrow, this post is going to talk about my own experience. It's going to be mostly about me and being an introvert.

## Remote working and being an introvert

I've been _almost_ full-time remote worker for almost 10 years. 
I'm saying _almost_ because in practice, I'm moving from time to time for profesional reasons (conferences, meetings).
However, for my daily job, everything is done from home.
Before being a remote worker, I was driving a lot: my job was in Nantes, around 45km from home.
That was about ~90km a day, but more importantly between 2 and 3 hours of commute a day.
The day I switched jobs, working for VMware on the Groovy language, the first shock was that I was recovering those 2 to 3 hours a day.
That's a lot of time to spend with your kids (dropping them at school, driving them to sports, ...) or doing housekeeping (fixing, gardening, sports, ...).
I won't come back to those advantages because they are mostly known, the only real drawback to me is being capable of handling your own work hours, that is to say, contrary to the belief, not working _too much_.

The thing I want to talk about is this comment from Antonio Goncalvés who said:

[quote]
____
Dump your coffee maker, go out, see people, it's important to see other human beings!
____

This https://twitter.com/CedricChampeau/status/1173893698997936130[made me react] so I wanted to come back to this topic.

First, this advice only works if you live in a city, which is not my case.
I (intentionally) live in the countryside, 5kms from the town center.
A "small coffee break" turns into an expedition in those conditions.

But let's come to the core of the topic: "It's important to see and talk to human beings", which relates to the _necessity not to be alone_.
This is a topic I care about and resonates with a question I often answered when I'm talking about remote work:

[quote]
____
But aren't you tired of being alone and not seeing anybody?"
____

Honest answer: **no**.

I understand people who need this, but **don't think everybody works like you** and _need_ to see other people.
Some folks like me live perfectly well without seeing anybody.
I can spend days alone, without me going mad or missing any social relationship.

I'm part of this population called the _introverts_.

- An _introvert_, contrary to the popular belief, isn't antisocial, selfish or without any kind of empathy.
- An _introvert_ is someone whose energy is drained by the crowd, by social relationships. It's the opposite of an _extravert_ who needs to see people to recover energy.
- An _introvert_ is someone who can't stand smalltalk, because they don't bring anything to him/her except from draining their energy.
- An _introver_ is someone who can talk hours on a topic (s)he's passionate about because it's _worth their energy_.

When I was a kid I already avoided being in a group of people.
I didn't have many friends (but the friends I had back then I still have them today).

I always freaked out at the idea of being in a group where I knew nobody, be it at school, at sport or even family parties.
Even if I _knew_ someone, being _in a group_, having to entertain social relationships was of extreme difficulty (and it still is today, to some extent).
Everything I cared as a child about back then was being "excellent" at school and my parents be proud of me.
This caused me to get some nicknames ("the nerd"), being hassled or even get some not so nice words written on the back of my classroom photographs, for a large part of my childhood.

As an example, I always refused to go to summer camps (the only experience I got, a week in a stud farm, was so painful to me I still remember it).
I also refused going to snow camps.
However, I _did_ accept going to England, Ireland and Spain with school, not without fighting myself, because I knew I could learn something out of it, but also because I knew I would be in a small group with a friend.

Similarly, having to stand in front of the rest of the classroom to recite a poem, or worse, sing, was pure torture to me.
On the contrary, I loved being at the University of Science in Nantes, where I could spend some time with 2 or 3 friends max at the coffee shop, discussing with them.
I didn't like much the software engineering school I joined to after that, where I had to be extremely creative to avoid the student integration parties, after-work parties and all those driking games most students were fond of: it was incredibly difficult to be recognized as a person without being excluded because I didn't participate in those events.

Let's talk about those "integration" parties. What's fun for some, being drunk, "gently" humiliating others, was just disgust and fear for me.

Now that I think about it, few people know it, but I spent my whole scolarity in Nantes, not because everything was available there (it was, really), but because I was petrified at the idea of beling "alone" in a new University, an engineering school, somewhere else at the other end of France, ... 
I remember a teacher who blamed me for not going in a well known French school despite I had the "capacity" do it. 
In retrospect I don't think it was a big mistake, I'm quite happy where I am today!

## I would never hire someone like you!

Everything I explained may sound surprising from someone who, today, gives talks at conferences, sometimes in front of hundreds of people, which sounds a bit irrealistic. 
So what's the difference?

Well the difference is that when I talk to you in a such a context, I **understand the topic** (or at least I think I understand it ;)).
I can talk to you openly because I know the questions I will get are directly related to the topic I'm talking about.
There's almost no room for the _unknown_.

That's also for this reason that it's still very difficult to me, even today, to reach out to others.
I am still completely incapable of doing small talk.
This goes even beyond that: I've traveled abroad a number of times, multiple times in the US for example, but I _never_ went outside alone to visit (at best I can walk an hour or two in the neighorhood).
That's because doing this drives me outside of my comfort zone: having to talk to people I don't know, ordering a meal, asking for directions: all this is draining my energy. It's always easy to say you should go out of your comfort zone when doing this is not a trial for you.

However, if I know one or two people and that they kindly ask me to join them, in most cases it will be fine and I would appreciate visiting!
Everybody's telling me I'm incredibly lucky to travel. 
Well, maybe, but I, for one, hate this, at least I hate it if I have to do this without my family...
Even going to Paris, realizing how many people live there, feeling like an ant in the anthill, remind me how much I hate this!

As a consequence, I avoid as much as I can "parties" like speaker dinners or corporate events.
They are often described as the _must do_ of networking. 
While it's true that you can learn a lot in those events, they are also incredibly stressful to me.
When I join them, most of the time I'm trying to identify someone I know, stick with them but I would often leave early and I have to go to my hotel room alone to recover.
I wouldn't necessarily _sleep_, as some people think I do: often I would work late in my hotel room, I just need to be _alone_.
The most terrifying thing to me in those parties is when conversations become _extra-professional_ which is something I have no "skill" for.
Some would say I'm a boring guy, that there's no interest in talking to me and that's probably right if you're looking for someone with an extraordinary life, mine is not that much :)

A natural conclusion that some people draw from this is that of course I can't be a good team player.
In fact I think that's quite the opposite: I value _trust_ like no one else and I think you can _trust_ me.
One shouldn't mix my incapacity to have simple inter-personal relationships with my capacity to have useful professional interactions, which is another totally different dimension.

As I explained, I'm regularly giving talks and I love more than anything else sharing knowledge and information, helping others.
I also enjoy working with people more competent than me so that I can continue to learn and make progress: in this context working in a team is extremely effective.

Also, it's not because you're working remotely that you don't see anyone and that, effectively, you work _alone_.
It's quite the opposite: we work as a team.
As other teams we do daily standups (via hangouts or Slack), we organize work.
Sometimes we even do face to face meetings or leverage conferences to meet together and do some work.
So it's not because you're an introvert that it's a problem: I think my colleagues would tell you that it works pretty well actually.

In short, don't be afraid of this aspect: being alone is not a problem for everyone. Maybe it is for you, but definitely not for everyone.
On the opposite, being alone can also boost productivity: no interruption, no useless meetings, ability to focus on a problem for hours etc...
Being introvert doesn't mean either that someone is not capable of working in a team: it doesn't prevent _at all_ from helping others, colleagues or customers.
On the contrary, the professional relationship is focused.

So how does it work in practice?
At Gradle, almost everybody is working remotely.
For the socializing aspect, we have an _optional_ weekly meeting, called "coffee time", that anyone willing to can join and chat about extra-work topics.
Some need this, I don't: the good thing is that we recognize not everybody's the same.
Actually I would be in difficulty to join this meeting and know _what_ to talk about.
Sometimes I even try to avoid being the first one joining a remote call to avoid having to do some small talk because I'm so uncomfortable with this.

However, again, talk to me about a topic I know about or that I'm passionate about. Ask me about a problem to solve, ask me about helping others and I'll be happy to do so because there's no room for the unknown.

Similarly if we meet in person at a conference and that you wish to talk to me, go ahead: it's very likely I will enjoy our conversation: I had several times the opportunity to talk to very famous folks of the Java community (James Gosling, Brian Goetz, Mark Reinholds, ...) and so many others but I just _couldn't_, it was, physically, impossible to me. 

In fact I have so much difficulties coming to someone and opening a discussion that if you do the first step it's _much_ easier.

So: don't be surprised if I walk the area 3 times in a row without asking for directions. Don't be surprised if I don't phone or text you. I'm not ignoring you.

## Don't be ashamed of being an introvert but make others understand what it means

Last, in a https://twitter.com/CedricChampeau/status/1173893698997936130[Tweet] I was saying that I was "healing myself".
That's both true and false at the same time.
It's true because I'm aware of the importance of the ignorance of a lot of people about this condition of mine, so I try to work, for example, speaking with others in different contexts.
I am for example the secretary of my karate club, which forces me to talk to people I don't know.
I am also the coach of my younger boy's (10 yo) basketball team, which I enjoy very much doing: it's an activity which allows both spending time with my kid, requires some public communication skills and is very gratifying (seeing kids happy to play, win a match, share this with their parents etc...).

Last but not least it's also a message for my son who I know feels very much like me: he also has difficulties speaking to others and I know he works hard to get accepted. He's also so proud when he gets recognition from his community.

It took me years to put a name on what I am: I'm an _introvert_ and often I have to fight myself not to be ashamed of this.


