= Pourquoi je soutiens Benoît Hamon
Cédric Champeau
2017-03-01
:jbake-type: post
:jbake-tags: politique,ps,hamon
:jbake-status: published
:source-highlighter: prettify
:id: soutien-hamon-draft

Cette élection présidentielle est unique. A bien des égards. La première raison, qui m'est insupportable, est que pour la première fois, une candidate FN, Marine Le Pen, est en position de gagner cette élection: un mirroir de ce qui se passe à l'échelle mondiale, avec un repli sur soi et une montée inquiétante du populisme. La seconde, parce qu'évidemment jamais le rejet des politiques en place n'aura été aussi important. Pour autant, c'est aussi une opportunité, pour une fois, de changer radicalement de société. Les choix qui s'offrent à nous sont particulièrement clairs: une droite extrêmement dure avec Fillon et Le Pen, ou une gauche sans compromis avec Hamon ou Mélenchon. Sans oublier, bien sûr, l'outsider désormais favori Macron, dont je ne sais toujours pas s'il a des convictions ou s'il est simplement le reflet de la nature, qui a horreur du vide (je ne sais pas où voter, allons là où tout le monde semble se rallier).

Pour ma part, je vote par conviction. J'aurais bientôt 38 ans, et je dois dire que jamais, je n'ai été si proche des idées d'un candidat. Je le suis depuis plusieurs mois, bien avant la primaire, et mes amis proches savent que je leur en parlais et que je croyais en sa victoire. Dans ce billet, je veux vous donner quelques pistes pour lesquelles je soutiens Benoît Hamon, et pourquoi je vous invite à le rejoindre.

NOTE: A mes lecteurs habituels, ce billet n'a rien à voir avec mes interventions techniques. Libre à vous de l'ignorer. Par ailleurs, je souligne évidemment que ce qui est écrit ici n'engage que moi, et personne d'autre que moi.

== Le revenu universel

Commençons par le revenu universel, parce qu'il est le plus clivant. Même pendant la primaire des gauches, j'ai entendu des absurdités incroyables à son sujet, ou des questions très orientées des journalites simplement destinées à décridibiliser cette proposition. Pourtant, c'est une idée neuve, défendue par de nombreux économistes, http://www.sudouest.fr/2017/01/25/dix-economistes-defendent-le-revenu-universel-de-Benoît-hamon-3137718-705.php[de droite comme de gauche], ainsi que d'éminents chefs d'entreprise, tels http://www.numerama.com/politique/232346-elon-musk-juge-le-revenu-de-base-necessaire-face-aux-progres-de-la-robotique.html[Elon Musk, le fondateur Tesla, Space X, devenu richissime avec la revente de PayPal], ... Pas spécialement un exemple de ratage. Rappelons son principe de base: donner, à chaque citoyen, un revenu identique (dont le montant varie selon les propositions), universel, indépendemment de ses resources, à compter de sa majorité. A droite, on http://www.liberation.fr/debats/2017/02/06/non-le-revenu-universel-ne-decourage-pas-le-travail_1546717[crie alors à l'assistanat]. A gauche, on hurle qu'il ne faut pas donner aux riches qui ont déja bien assez.

Mais le monde change. Le travail change. Quiconque vous dit le contraire est soit aveuglé, soit vous ment. Je travaille dans l'informatique, et par mon activité professionnelle qui m'amène à rencontrer de nombreux développeurs du monde entier, je pense être assez bien placé pour voir que ce je développe, ce qui arrive, est une nouvelle révolution industrielle (mais pas seulement, les services sont aussi touchés). 

En France, vous aurez déja remarqué que les caissières se font moins nombreuses, qu'il n'y a plus personne aux péages, que le métro n'a plus de conducteur, qu'on nous vend du pain frais dans un distributeur... Mais nous sommes très en retard. 

- En Chine, où sont fabriqués nos précieux smartphones, les monstrueuses usines employant des dizaines de milliers d'ouvriers ont déja entamé leur migration vers une http://alltrends.over-blog.net/2017/02/une-entreprise-remplace-90-de-ses-employes-par-des-robots.html[robotisation intégrale]. 
- A Singapour et aux Etats-Unis, les http://www.lemonde.fr/economie/article/2016/08/25/les-premiers-taxis-sans-chauffeur-roulent-a-singapour_4988089_3234.html[taxis sont remplacés par les voitures autonomes] (notez l'ironie, au passage: pour un Fillon ou un Macron dont le modèle est http://www.streetpress.com/sujet/1488276642-coursier-velo-se-fait-virer[l'Uberisation de la société, l'auto-entreprenariat], là où il est clair depuis des mois que le but de cette même entreprise est le 0 salarié...). Des http://thegoodlife.thegoodhub.com/2016/05/19/otto-camion-se-conduit-seul/[poids lours conduisent tout seuls sur des centaines de kilomètres]. http://www.lemonde.fr/technologies/article/2013/12/02/des-paquets-livres-par-drones-d-ici-cinq-ans_3523489_651865.html[Amazon livre par drones]. 
- Au Japon, ce sont mêmes des http://www.numerama.com/tech/221747-une-i-a-remplace-34-employes-dune-assurance-au-japon.html[employés d'une assurance qui sont remplacés par une intelligence artificielle]. 
- Watson, l'IA développée par IBM, a déja https://www.letemps.ch/sciences/2016/09/22/un-outil-diagnostic-medical-nomme-watson[diagnostiqué une leucémie que les médecins avaient ratée].
- Un https://www.theguardian.com/technology/video/2017/feb/28/meet-handle-the-two-wheeled-four-legged-hybrid-robot-video[robot pourra bientôt transporter des charges lourdes à notre place]

Quoi qu'on en pense, à moyen terme, la *révolution robotique* est en marche, et c'est une bonne chose. Bien sûr, on ne parle pas d'un remplacement à court terme. Tout celà est progressif. Des métiers vont disparaître, d'autres se transformer, d'autres encore vont apparaître, mais il est indéniable que le volume de travail global disponible à l'humain fond comme neige : nous sommes toujours plus nombreux sur la planète, le https://data.oecd.org/chart/4KKb[PIB augmente, pour autant le volume d'heures travaillées évolue peu]. L'étude la plus optimiste de l'OCDE indique que http://www.lemonde.fr/economie/article/2016/05/20/pour-l-ocde-9-des-emplois-sont-menaces-par-les-robots_4923165_3234.html[près de 10% des emplois sont menacés à court terme]. Une autre étude parle elle de http://www.francetvinfo.fr/replay-radio/nouveau-monde/les-robots-le-chomage-et-les-emplois-de-2030_1777669.html[50% des emplois remplaçables par des robots à l'horizon 2030]. Lorsqu'on choisit une politique, il ne faut pas penser à court terme, mais à nos enfants. Même s'il est idiot d'affirmer que le travail va disparaitre (qui peut sérieusement le croire ?), il se transforme, et il faut embrasser cette transformation.

J'en suis convaincu, les politiques qui ignorent ces changements vivent dans un monde qui n'existe plus: ils achètent leur pain au chocolat à 10 centimes, font leurs courses chez Prisunic et rêvent de payer leurs assistants parlementaires européens en Francs. Ignorer les changements du travail, c'est ignorer l'avenir, s'aliéner à ceux qui embrassent ce changement, perdre notre souveraineté. Au lieu de combattre ce futur, il faut au contraire s'y préparer et repenser notre société autour de ces changements. L'automatisation, la robotisation, n'engendre pas de perte de valeur: celle-ci est toujours présente, les prix ne baissent en général pas: la productivité augmente et on réduit la pénibilité. Deux choix de société s'engagent alors: profiter de cette amélioration pour vivre mieux, ou une fuite en avant productiviste. A ce sujet, je conseille la lecture de https://crew.co/blog/why-you-shouldnt-work-set-hours/[ce billet] à mes lecteurs anglophones: ou comment le temps de travail est fonction des évolutions de la société, pas une constante.

Ceci appelle à une révolution fiscale: là où aujourd'hui on taxe le travail, il faudra demain http://www.lci.fr/elections/quelle-est-donc-cette-taxe-robots-proposee-par-Benoît-hamon-qui-seduit-jusqu-a-bill-gates-2026781.html[taxer les robots], comme http://fortune.com/2017/02/18/bill-gates-robot-taxes-automation/[le propose aussi Bill Gates]. Si ce terme peut faire sourire, il cache en réalité de nombreuses ramifications: évasion fiscale en particulier. Quelle pire injustice que de voir nos petites entreprises crouler sous des 30% de taxes, lorsque les grandes entreprises étrangères qu'on utilise tous (smartphones, distribution), qui robotisent, automatisent et n'embauchent quasiment pas, placent "leur" argent dans des paradis fiscaux et ne paient pas d'impôts, grâce à des montages financiers complexes avec la complicité de nos cabinets comptables ? Ne marchons nous pas sur la tête ? 

Alors, oui, on peut continuer à sourire, dire qu'il faut baisser les charges pour les entreprises et les salariés (ce qui serait une bonne chose), mais si on n'embrasse pas cette virtualisation de l'économie, on ne fait que réduire l'assiète des cotisations, et se ruiner un peu plus.

Alors que vient faire le revenu universel là dedans ? Il permet:

- de mettre fin à la grande pauvreté, en particulier en remplaçant le RSA, belle idée mais tellement complexe que nombreux sont ceux qui y ont droit et ne le demandent pas. Par ailleurs, si le revenu est effectivement universel, l'argument de la fraude aux aides ne tient plus: tout le monde y a droit, point.
- de favoriser le temps partiel. Dans certains Etats, comme les http://www.lemonde.fr/economie/article/2016/02/03/aux-pays-bas-on-travaille-en-moyenne-30-heures-par-semaine_4858496_3234.html[Pays-Bas, c'est déja la norme, y compris chez les hommes], réduisant ainsi les inégalités homme-femme. Le PIB de ce pays n'a pas chuté, les employés n'en sont que plus heureux. 
- de maintenir l'emploi. Des histoires d'agriculteurs qui travaillent comme des fous et ne s'en sortent plus, on en lit tous les jours. Avec https://twitter.com/Benoîthamon/status/836905767571697664[350€] par mois, franchement, vous resteriez? Je connais personnellement l'un d'entre eux qui a fini par abandonner. Avec le revenu universel, on permet à ces travailleurs pauvres de rester en poste.
- de choisir de travailler plutôt que rester à la maison. Je ne sais pas pour vous, mais le nombre de fois où j'ai entendu quelqu'un me dire "avec mes frais de garde et de transport, ça me revient plus cher d'aller travailler que de rester chez moi". Pas franchement encourageant, non?
- de valoriser des activités non commerciales mais importantes pour la société : travail associatif, aides à la personne, ...
- de partager le travail: à coût égal pour une entreprise, il sera possible de prendre 2 salariés au lieu d'un seul, et ainsi donc réduire les risques de TMS (pour les travaux manuels) ou burn-outs : il existe une limite physique à la productivité.

En revanche, le RU ne rend pas les riches plus riches. C'est un *revenu*. En conséquence, il est imposable. Il s'ajoute donc à votre salaire et suivant vos revenus, vous devrez payer ou non des impôts dessus. Il est donc incorrect de dire que ça coute 400 milliards (ou plus). En pratique, il coûte sensiblement moins, en particulier si son implémentation se fait _via_ un crédit d'impôt. La justice fiscale est maintenue. Le soumettre à conditions de ressources, c'est augmenter son coût intrinsèque (gestion, contrôles) ou inciter à la fraude pour quelque chose qui ne change au final rien. Quant à l'argument de l'incitation à l'oisiveté, il me fait doucement sourire. A tous ceux qui me l'ont avancé, je leur ai posé une question simple: si on vous donnait 600€ par mois, est-ce que vous quitteriez votre boulot ? Est-ce que ça vous suffirait ? Je pense que je n'ai pas besoin de vous donner les réponses...

Alors, certains taxent cette proposition d'irréaliste, utopique, irréalisable et j'en passe. Ils doutent de sa crédibilité. Mais que proposent-ils ? Toujours les mêmes solutions ! Réduire les charges des entreprises (merci Fillon pour son exonération sur les bas salaires, effet d'aubaine pour n'augmenter personne, alors que la répartition de la valeur n'a http://www.inegalites.fr/spip.php?page=article&id_article=1156[jamais été aussi dévaforable aux pauvres et classes moyennes]). Augmenter la TVA (belle justice fiscale !). Qui se souvient, à l'inverse, de la baisse de la TVA pour la restauration, en l'échange, soit disant, d'emplois et de baisses de prix ? Qui se souvient encore du badge http://www.lemonde.fr/emploi/article/2014/09/24/pierre-gattaz-oui-il-est-possible-de-creer-un-million-d-emplois_4493160_1698637.html[1 million d'emplois de Pierre Gattaz] en l'échange du pacte de compétitivité ? Travailler plus, en défiscalisant les heures supplémentaires, encore une mesure populaire, mais qui ne crée pas d'emplois (la vraie injustice), et n'est qu'un pansement sur une jambe de bois: est-ce que cette politique a déja une seule fois marché ?

Autre question: qui peut encore croire que repousser l'âge de la retraite est une solution, alors même que les seniors sont http://www.lemonde.fr/societe/article/2011/07/29/chomage-les-seniors-sont-indesirables-dans-les-entreprises_1553945_3224.html["trop vieux pour travailler" dès 50 ans] ? Je ne suis fondamentalement pas contre repousser l'âge de la retraite (qui finalemement va de pair avec l'augmentation de l'espérance de vie), mais faire ça alors même que nos seniors sont au chômage n'a aucun sens. Il faut d'abord revaloriser l'expérience, changer notre vision. Comment peut-on imaginer créer des emplois en faisant travailler plus ceux qui ont la chance d'en avoir un, http://www.francetvinfo.fr/replay-radio/on-s-y-emploie-de-philippe-duport/l-inquietante-progression-des-troubles-musculo-squelettiques_1790187.html[quitte à les briser] ? 

60 milliards ont été engloutis dans le CICE, pour quel résultat ? Autre solution classique, se reposer sur une croissance, dont les prévisions sont systématiquement revues à la baisse, et donc les conséquences sur notre planète commencent sérieusement à se faire sentir ? Ou faciliter le licenciement, en croyant dogmatiquement que ça facilite l'embauche ? Ce dont ont besoin les entreprises, ce n'est pas de pouvoir licencier. Personne ne veut licencier par plaisir. Ce qu'il faut, c'est de la stabilité. Connaitre les règles du jeu à l'avance, et qu'elles ne changent pas tous les jours, ainsi qu'une juste concurrence : que les petites paient les mêmes impôts que les grosses, et que les différences de législation entre partenaires commerciaux ne soient pas un frein aux entreprises locales (donc, un protectionnisme _raisonné_). Alors, dites-moi, qui est irréaliste et utopique ?

Alors, on va nous parler de "valeur travail". Ou la réalisation par le travail. Est-ce là une valeur que je veux transmettre à mes enfants ? Non. Si le travail est important, il ne doit pas être le critère de réalisation, en particulier dans une société ou le travail se raréfie. C'en est de plus insultant pour tous ceux qui ne trouvent pas d'emploi, ou pour ceux qui s'investissent autrement (associations, sportifs, artistes) et contribuent à la grandeur de notre pays. Ce que j'enseigne à mes enfants, c'est qu'il faut se donner à fond et ne pas se fermer de portes. Je leur apprends la tolérance. Je leur apprends à apprécier la chance qu'ils ont par rapport à d'autres. Je leur apprends que l'effort est récompensé, mais que parfois, la vie est injuste. Travailler, oui, mais choisir. Le choix, la liberté sont la clé de la réalisation.

Et d'avenir, parlons-en.

== La révolution écologique

Lorsqu'on parle de révolution industrielle, on ne peut ignorer la transition écologique à mener, et son potentiel énorme en termes d'emplois. La France a trop longtemps dirigé tous ses crédits vers le nucléaire, en en ignorant volontairement le coût réel (démantèlement, notamment) et son impact sur l'environnement (bien sûr, un accident n'arrive jamais). Mais le plus gros mensonge, c'est encore notre fameuse indépendence énergétique. Faut-il rappeler d'où vient le combustible si précieux dont nous avons besoin ? Pour autant, il ne faut pas être naif: sortir du nucléaire prend du temps, mais c'est aussi une énorme opportunité. En échelonnant dans le temps, comme le propose Benoît Hamon, on permet de maintenir notre capacité de production, tout en ouvrant de nouvelles voies de développement, créant des emplois. La catastrophe serait de faire comme en Allemagne, où toutes les centrales ont été remplacées par des centrales à charbon, dont le bilan carbone est redoutable... Cette http://www.electricitymap.org/[carte interactive] est plus que parlante...

Mais l'écologie ne se limite pas au nucléaire. L'opposition ferme de Benoît Hamon aux perturbateurs endocriniens est un autre exemple de ce que j'aime dans sa vision: il est temps d'en finir avec la dictature de la croissance, qui détruit notre environnement et provoque de graves maladies. Penser que je puisse être responsable du futur cancer de mes enfants m'est juste impossible: si je peux faire quelque chose aujourd'hui, quitte à sacrifier un peu de confort (je suis le premier à changer de smartphone tous les 3/4 ans, mais en ai-je vraiment besoin ?), faisons-le. Il existe des solutions: circuits courts, production raisonnée, retour à une agriculture prenant en compte les spécificités régionales, réduction de notre consommation de viande, ... Nous devons aussi nous responsabiliser en tant que consommateurs: acheter toujours moins cher, c'est inciter à la baisse des salaires ou à la délocalisation.

== La République

Un des derniers points que je souhaite discuter ici est ma vision de la République. Tout d'abord, je souhaite le retour au septennat. Je pense que le passage au quinquénat a été une catastrophe, contribuant à la peopolisation de la politique: on ne cherche plus à faire un projet, on parle tout de suite de la prochaine élection. Même si je n'ai pas d'idée précise de ce que doit être la prochaine République, il me semble clair que celle-ci est à bout de souffle. Conçue pour le Général de Gaulle, l'homme providentiel. Je pense qu'il faut revoir le rôle de Président, et qu'il ne soit plus qu'un garant de nos institutions. Pour celà, il nous faut une assemblée consistuante. Benoît Hamon n'en parle pas spécialemement, et c'est peut-être un des points où je suis plus en accord avec un Mélenchon que lui: il faut bien des points de désaccord. En particulier, je trouve l'idée du 49-3 citoyen avec seulement 1% du corps électoral potentiellement dangereuse : la Manif pour Tous aurait pu bloquer le mariage homosexuel (oui, je suis de ceux qui pensent que donner des droits égaux à tous les citoyens n'est pas supprimer vos propres droits), ou, du temps de Mitterand, je doute que la peine de mort aurait pu être abolie. En clair, je suis plutôt pour une proportionnelle intégrale, répondant à une crise de représentativité qu'entretient élégamment le FN. Mais je suis aussi surtout pour la https://fr.wikipedia.org/wiki/Tirage_au_sort_en_politique#Stochocratie[stochocratie], où le fait de tirer au sort des représentants qui, eux, éliront ceux qui nous gouvernent.

== Laïcité et peur de l'autre

Une de mes plus grandes désillusions de l'ère Hollande. C'est là que le Parti Socialiste m'a perdu. J'ai été affligé par la Loi Renseignement. Non seulement elle est liberticide, mais elle est aussi dangereuse pour nos entreprises, réduisant considérablement les sécurités et garanties qu'elles peuvent mettre en place pour leurs clients. Mais le plus grave, le divorce, ce fut la déchéance de nationalité. Sous prétexte de protéger nos concitoyens, nous créons deux catégories de personnes, ce qui est le contraire même des fondements de notre République. Plus encore, une trahison des valeurs de gauche. Aux élections qui ont suivi, pour la première fois de ma vie, je n'ai pas voté PS. Fort heureusement, cette mesure n'est jamais passé, j'aurais eu honte, franchement.

En ce qui concerne le débat sur la laïcité, là encore, je suis à 100% derrière la position de Benoît Hamon: la loi 1901 et rien que la loi 1901. En clair, il s'agit de respecter la liberté de culte. Et respecter _toutes_ les religions. Point. Il faut être sacrément culotté (ou aigri), pour dire "Benoît Hamon est en résonance avec une frange islamo-gauchiste". Malek Boutih, je vous le dis sincèrement, cest propos sont une honte pour la gauche. Les simples sous-entendus de cette phrase me dégoutent. Pire, vous avez donné des arguments à l'extrème droite, que nous combattons de tout notre coeur. C'est indigne et tellement typique de cette gauche archaïque (un paradoxe quand vous vous qualifiez de progressiste) et loin de ses valeurs. Après de telles sorties, ne soyez plus surpris que les gens votent FN et vous bottent les fesses aux élections.

Non, je crois aux valeurs humaines. Le FN tente de nous faire croire que 2000 migrants sont responsables du chômage en France, par pitié, non. Pire encore, les migrants violent nos femmes et mangent nos enfants. Et ils n'avaient qu'à https://s2.qwant.com/thumbr/0x0/d/4/f17a15e2d5fe46ad9f63b25011b969/b_1_q_0_p_0.jpg?u=http%3A%2F%2Fd.ibtimes.co.uk%2Fen%2Ffull%2F1410255%2Faleppo-syria.jpg&q=0&b=1&p=0&a=1[rester chez eux], ou http://www.bfmtv.com/international/migrations-l-europe-sous-le-choc-apres-la-photo-d-un-enfant-mort-noye-911785.html[apprendre à nager]. Nom d'un chien, où est passé le coeur de la France ? Doit-on laisser mourrir tous ces gens, les suspecter des pires crimes, ou être à la hauteur de notre histoire, nous, le pays des Droits de l'Homme ? Se dire que l'allemagne accueille des millions de migrants dans le même temps où l'on fait des procès à http://www.francetvinfo.fr/monde/europe/migrants/aide-aux-migrants-cedric-herrou-le-passeur-condamne_2056739.html[Cédric Hérrou]. Dois-je vous rappeler ce que la stigmatisation nous a apporté voici 80 ans ? Ce monde tourne sur la tête...

== Les cas Macron / Mélenchon

Pour terminer, parlons rapidement d'Emmanuel Macron et Jean-Luc Mélenchon. A la lecture de ce billet, certains peuvent se dire que je pourrais choisir Mélenchon. C'est vrai, lui et Hamon partagent beaucoup d'idées, tout comme les Verts et à ce titre je suis dépité qu'un accord entre les 3 n'ait pas eu lieu. C'était, à mon humble avis, une opportunité unique pour la gauche compte-tenu de la conjecture actuelle. Je pense, pour ma part, que Benoît Hamon a véritablement compris la transition économique qui nous attend et a une personnalité moins clivante. Les solutions de repli sur soi ne fonctionneront pas. Pas plus que les solutions de Macron, qui reste une énigme. Ses discours sont d'une platitude déconcertante, ses solutions en matière d'économie sont peu ou prou les mêmes que celles de Fillon (libéralisation à outrance du marché du travail), et pourtant... il monte, il monte... Le ralliement de François Bayrou, celui là même qui disait, il y a quelques semaines, que http://www.lefigaro.fr/elections/presidentielles/2017/02/22/35003-20170222ARTFIG00291-avant-de-le-soutenir-bayrou-attaquait-durement-macron.php[Macron était piloté par les banquiers] (ce qui est toujours possible puisqu'il refuse d'indiquer qui le finance)... Je peux me tromper, mais je ne crois pas non plus à la fin du clivage droite-gauche. Nos idées sont différentes. Nos visions de la société sont différentes. Progresser, c'est choisir une vision, et y aller. Faire cohabiter des idées si différentes au sein d'un même gouvernement ne peut conduire qu'à prendre de "petites" décisions ne frustrant personne. Soyez rassurés, cependant, je ne mets pas Emmanuel Macron au même niveau que François Fillon ou Marine Le Pen...

En conclusion, je ne suis pas crédule non plus, tout ceci n'est pas réalisable en un jour et c'est pour celà je j'aime l'approche de Benoît Hamon: *jamais* il ne s'est présenté comme le candidat providentiel, qui a la réponse à tout. Il faut laisser le temps à une politique de se mettre en place (d'où le septennat). Hamon est un homme qui a une vision, il a travaillé ses dossiers, mais c'est aussi un https://www.Benoîthamon2017.fr/2017/02/22/rejoignez-le-conseil-citoyen/[team player]. Toutes ses mesures sont réfléchies, travaillées, et vont dans le sens d'un projet à long terme: un avenir désirable.

La société que l'on souhaite pour nos enfants. C'est à eux que je pense en le choisissant. Ce dont ils ont besoin, c'est d'espoir. Je ne veux pas qu'ils grandissent dans ce monde qu'on nous promet:

- https://www.marianne.net/societe/auchan-city-de-tourcoing-apres-la-fausse-couche-d-une-caissiere-les-inquietants-recits-de
- http://www.streetpress.com/sujet/1488276642-coursier-velo-se-fait-virer
- http://www.bfmtv.com/societe/vaucluse-suicide-d-un-agriculteur-dont-l-exploitation-etait-en-difficulte-963138.html
- https://francais.rt.com/france/19526-hauts-seine--tabassee-pour

Et vous ?


